<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Inicio de Sesión</title>
</head>
<body>
    <h2><b>Iniciar sesión</b></h2><br>
    <?php if (isset($info)) echo "<p style='color:red;'>$info</p>"; ?>
    <form action="index.php?c=login" method="POST">
        <label for="username">Usuario:</label>
        <input type="text" name="username" required><br><br>
        <label for="password">Contraseña:</label>
        <input type="password" name="password" required><br><br>
        <input type="submit" name="login" value="Iniciar sesión">
    </form>
</body>
</html>
