<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tienda Online</title>
</head>

<body>

    <?php

    if (isset($_SESSION['user'])) {
        echo "<h3>Bienvenido, " . $_SESSION['user']->getUsername() . "</h3>";
        echo "<a href='index.php?c=login&logout=1'>Cerrar sesión</a><br><br>";
    } else {
        echo "<a href='index.php?c=login&login=1'>Login</a><br><br>";
    }

    ?>

    <h1>Tienda Online</h1>
    <h3>Productos</h3>


</body>

</html>