<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Producto</title>
</head>

<body>

    <ul>
        <?php

        $image = "./public/img/" . $product->getImage();

        echo '<h2><a href="index.php?c=product&showUniqueProduct=1&product_id=' . $product->getId() . '">' . $product->getName() . '</a></h2>';
        echo "<img src='" . $image . "' alt='" . $product->getName() . "' width='200' height='300'><br><br>";
        echo '<p> ' . $product->getDescription() . '</p>';
        echo '<p>Precio: ' . $product->getPrice() . '€</p>';
        echo '<p>Cantidad disponible: ' . $product->getStock() . ' unidades</p>';

        if (isset($_SESSION['user'])) {
            echo '<a href="index.php?c=cart&addCart=1&product_id=' . $product->getId() . '&unitary_price=' . $product->getPrice() . '">Añadir al carrito</a><br><br>';
        }

        if (isset($_SESSION['user']) && $_SESSION['user']->isAdmin()) {
            echo '<a href="index.php?deleteProduct=1&id=' . $product->getId() . '">Eliminar Producto</a><br><br>';
        }
        ?>
    </ul>


    <a href="index.php">Volver a la pagina de inicio</a>

</body>

</html>