<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Foro - Pagina Principal</title>
</head>

<body>

    <h1>5chan</h1>
    <?php

    if (!isset($_SESSION["user"])) {
        echo "<p>Bienvenido, puedes iniciar sesión <a href='index.php?c=login&login=1'>aquí</a></p><br>";
    } else {
        echo "<h3>Bienvenido, " . $_SESSION["user"]->getUsername() . "</h3>";
        echo "<a href='index.php?c=login&logout=1'>Cerrar sesión</a><br><br>";
    }

    echo "<h2>Foros</h2>";
    echo "<hr>";
    if (isset($_SESSION['user']) && $_SESSION["user"]->getRole() == "admin") {
    ?>

        <h3>Crear un foro</h3>
        <form action="index.php?c=forum" method="POST" enctype="multipart/form-data">
            <input type="text" name="forumTitle" placeholder="Titulo del foro" required><br><br>
            <textarea name="forumDescription" placeholder="Descripcion" required></textarea><br><br>
            <input type="checkbox" name="visible" checked="checked" value="Visible">
            <label for="visible">Visible</label><br>
            <label for="forumImage">Imagen: </label>
            <input type="file" name="forumImage" accept="image/jpeg, image/png"><br><br>
            <input type="submit" name="addForum" value="Crear foro">
        </form><br>

    <?php
    }

    foreach ($forums as $forum) {
        if ($forum->isVisible() || $forum->getUser()->getId() == $_SESSION['user']->getId()) {
            echo "<div class='forums'>";
            echo '<h2><a href="index.php?c=forum&showForum=1&forum_id=' . $forum->getId() . '">' . $forum->getTitle() . '</a></h2>';
            echo "<p>" . $forum->getDescription() . "</p>";
            if ($forum->getImage()) {
                echo "<p><img src='" . $forum->getImage() . "' alt='Imagen del foro' width='200' height='150'></p><br>";
            }
            echo "</div>";
        }
    }
    ?>

</body>

</html>