<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo $theme->getThemeTitle() ?></title>
</head>

<body>

    <?php

    echo "<h1>" . $theme->getThemeTitle() . "</h1>";
    echo "<h3>Creado por: " . $theme->getUser()->getUsername() . "</h3>";
    echo "<img src='" . $theme->getUser()->getAvatar() . "' alt='" . $theme->getUser()->getUsername() . "' width='50' height='50'></img>";
    if ($theme->getImage()) {
        echo "<p><img src='" . $theme->getImage() . "' alt='Imagen del tema' width='200' height='150'></p>";
    }

    echo "<p>" . $theme->getContent() . "</p>";

    if (isset($_SESSION["user"]) && $_SESSION["user"]->getRole() == "admin") {

        if (!$theme->isHidden()) {
            echo "<p><a href='index.php?c=theme&hiddenTheme=1&hideTheme=1&theme_id=" . $theme->getId() . "'>Ocultar Hilo</a></p>";
        } else {
            echo "<p><a href='index.php?c=theme&hiddenTheme=0&hideTheme=1&theme_id=" . $theme->getId() . "'>Mostrar Hilo</a></p>";
        }
    }

    echo "<hr>";

    if (isset($_SESSION['user']) && $_SESSION['user']->isActive()) {

    ?>

        <h4>Añade un comentario</h4>
        <form action="index.php?c=theme&theme_id=<?php echo $theme->getId(); ?>" method="POST">
            <input type="hidden" name="theme_id" value="<?php echo $theme->getId(); ?>">
            <textarea name="commentText" placeholder="Comentario..." required></textarea><br><br>
            <input type="submit" name="addComment" value="Subir Comentario">
        </form><br>


    <?php

    } else {
        echo "<p>Para comentar debes <a href='index.php?c=login&login=1'>iniciar sesión.</a></p>";
    }

    foreach ($theme->getComments() as $comment) {
        if (!$comment->isHidden() || isset($SESSION_['user']) && $_SESSION["user"]->getRole() == 'admin') {
            echo "<hr>";
            echo "<img src='" . $comment->getUser()->getAvatar() . "' alt='" . $comment->getUser()->getUsername() . "' width='50' height='50'></img>";
            echo "<h4>" . $comment->getUser()->getUsername() . "</h4>";
            echo "<p>" . $comment->getText() . "</p>";
            echo "<p>" . $comment->getDate() . "</p>";
            if (isset($_SESSION['user']) && $_SESSION['user']->getRole() == 'admin') {
                if (!$comment->isHidden()) {
                    echo "<p><a href='index.php?c=theme&hiddenComment=1&hideComment=1&comment_id=" . $comment->getId() . "&theme_id=" . $comment->getTheme()->getId() . "'>Ocultar Comentario</a></p>";
                } else {
                    echo "<p><a href='index.php?c=theme&hiddenComment=0&hideComment=1&comment_id=" . $comment->getId() . "&theme_id=" . $comment->getTheme()->getId() . "'>Mostrar Comentario</a></p>";
                }
            }
        }
    }

    ?>

</body>

</html>