<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Todos los usuarios</title>
</head>

<body>
    <h1>Todos los usuarios</h1>
    <hr>

    <?php
    foreach ($users as $user) {

        echo "<img src='" . $user->getAvatar() . "' alt='" . $user->getUsername() . "' width='50' height='50'></img>";
        echo "<p>" . $user->getUsername() . "</p>";

        if (isset($_SESSION['user'])) {
            echo "<p>Email: " . $user->getEmail() . "</p>";
        }

        if (isset($_SESSION["user"]) && $_SESSION["user"]->getRole() === "admin") {
            if ($user->isActive()) {
                echo "<p><a href='index.php?c=user&banned=0&banUser=1&user_id=" . $user->getId() . "'>Banear</a></p>";
            } else {
                echo "<p><a href='index.php?c=user&banned=1&banUser=1&user_id=" . $user->getId() . "'>Desbanear</a></p>";
            }
            echo "<p><a href='index.php?c=user&setAdmin=1&user_id=" . $user->getId() . "'>Dar Rol de Administrador</a></p>";
        }
    }
    ?>
</body>

</html>