<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap" rel="stylesheet">
    <title>Playlists - Inicio</title>
    <style>
        body {
            background-color: #302f2f;
            color: #FFFFFF;
            font-family: 'Poppins', Arial, sans-serif;
        }

        input[type="submit"] {
            font-family: 'Poppins', Arial, sans-serif;
            background-color: #00A431;
            color: #FFFFFF;
            border-radius: 5px;
            padding: 5px;
            text-decoration: none;
        }

        input[type="text"] {
            font-family: 'Poppins', Arial, sans-serif;
        }

        a {
            color: #00A431;
        }
    </style>
</head>

<body>
    <h2>Espotify</h2>

    <?php

    if (isset($_SESSION['user'])) {
        echo "<h3>Bienvenido, " . $_SESSION['user']->getUsername() . "</h3>";
        echo "<a href='index.php?c=login&logout=1'>Cerrar sesión</a><br><br>";

    ?>
        <h3>Crear Playlist</h3>
        <form action="index.php?c=playlist&addPlaylist=1" method="POST">
            <label for="playlistName">Nombre de la playlist:</label>
            <input type="text" name="playlistName" required>&nbsp;
            <input type="submit" value="Crear">
        </form><br>

        <hr><br>

        <h3>Subir Cancion</h3>
        <form action="index.php?c=song&addSong=1" method="POST" enctype="multipart/form-data">
            <label for="songName">Nombre de la cancion:</label>
            <input type="text" name="songName" required>&nbsp;<br><br>
            <label for="author">Autor:</label>
            <input type="text" name="author" required><br><br>
            <label for="duration">Duración (mm:ss):</label>
            <input type="text" id="duration" name="duration" pattern="^\d{1,2}:\d{2}$" placeholder="mm:ss" required>
            <small>Ejemplo: 03:30</small><br><br>
            <label for="mp3File">Subir Archivo MP3</label>
            <input type="file" id="mp3File" name="mp3File" accept=".mp3" required><br><br>
            <input type="submit" value="Subir">
        </form><br><br>
        <hr><br>

        <h3>Descubre <a href="index.php?c=song&viewSongs=1">Canciones</a></h3><br>


        <h2>Tus Playlists</h2>
    <?php
        if ($playlists) {
            foreach ($playlists as $playlist) {
                echo "<a href='index.php?c=playlist&playlist_id=" . $playlist->getId() . "'>" . $playlist->getTitle() . "</a><br>";
            }
        } else {
            echo "<p>No tienes playlists, ¿a que esperas?</p><br>";
        }
    } else {
        echo "<p>Bienvenido, puedes iniciar sesión <a href='index.php?c=login&login=1'>aquí</a></p><br>";
    }

    ?>

</body>

</html>