<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo $playlist->getTitle(); ?></title>
    <style>
        body {
            background-color: #302f2f;
            color: #FFFFFF;
            font-family: 'Poppins', Arial, sans-serif;
        }

        input[type="submit"] {
            font-family: 'Poppins', Arial, sans-serif;
            background-color: #00A431;
            color: #FFFFFF;
            border-radius: 5px;
            padding: 5px;
            text-decoration: none;
        }

        a {
            color: #00A431;
        }
    </style>
</head>
</head>

<body>

    <h1><?php echo $playlist->getTitle(); ?></h1>

</body>

</html>