<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap" rel="stylesheet">
    <title><?php echo $playlist->getTitle(); ?></title>
    <style>
        body {
            background-color: #302f2f;
            color: #FFFFFF;
            font-family: 'Poppins', Arial, sans-serif;
        }

        .heart {
            color: white;
            font-size: 40px;
            text-decoration: none;
        }
    </style>
</head>
</head>

<body>

    <h1><?php echo $playlist->getTitle(); ?></h1>
    <strong><?php echo "Creada por " . $playlist->getUser()->getUsername()  . " - " . $playlist->getNumberOfSongs() . " canciones" . " - " . $playlist->getTotalDuration() ?></strong><br>

    <?php if ($playlist->getUser() != $_SESSION['user']) {

        echo "<a class='heart' href='index.php?c=playlist&addToFavorites=1&playlistIdFavorite=" . $playlist->getId() . "'>&hearts;</a>";
    } ?>


    <hr><br>

    <?php

    if ($songs) {
        foreach ($songs as $song) {
            echo $song->getTitle() . " - " . $song->getAuthor() . "<br><br>";
            echo "<audio controls>";
            echo "<source src='" . $song->getUrlFile() . "' type='audio/mpeg'>";
            echo "</audio><br><br>";
        }
    } else {
        echo "<p>No hay canciones en esta playlist.</p>";
    }
    ?>

</body>

</html>