<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap" rel="stylesheet">
    <title>Playlists - Registro</title>
    <style>
        body {
            background-color: #302f2f;
            color: #FFFFFF;
            font-family: 'Poppins', Arial, sans-serif;
        }

        input[type="submit"] {
            font-family: 'Poppins', Arial, sans-serif;
            background-color: #00A431;
            color: #FFFFFF;
            border-radius: 5px;
            padding: 5px;
            text-decoration: none;
        }

        input[type="text"] {
            font-family: 'Poppins', Arial, sans-serif;
        }

        a {
            color: #00A431;
        }
    </style>
</head>

<body>

    <h2>Registro</h2>
    <?php if (isset($info)) echo "<p style='color:red;'>$info</p>"; ?>
    <form action="index.php?c=register" method="POST">
        <label for="username">Usuario:</label>
        <input type="text" name="username" required><br><br>
        <label for="password">Contraseña:</label>
        <input type="password" name="password" required><br><br>
        <input type="submit" name="register" value="Registrarse">
    </form>


</body>

</html>