<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap" rel="stylesheet">
    <title>Canciones</title>
    <style>
        body {
            background-color: #302f2f;
            color: #FFFFFF;
            font-family: 'Poppins', Arial, sans-serif;
        }

        input[type="submit"] {
            font-family: 'Poppins', Arial, sans-serif;
            background-color: #00A431;
            color: #FFFFFF;
            border-radius: 5px;
            padding: 5px;
            text-decoration: none;
        }

        input[type="text"] {
            font-family: 'Poppins', Arial, sans-serif;
        }

        a {
            color: #00A431;
        }
    </style>
</head>

<body>

    <h1>Canciones</h1>

    <h3>Tus canciones</h3>

    <!-- TODO: Aquí se mostrarán las canciones del usuario -->

    <h3>Todas las canciones</h3>

    <form action="index.php?c=song" method="POST">
        <input type="text" name="searchSong" placeholder="Buscar cancion">
        <input type="submit" value="Buscar">
    </form><br>

    <?php
    if ($songs) {
        foreach ($songs as $song) {
            echo $song->getTitle() . " - " . $song->getAuthor() . "<br><br>";
            echo "<audio controls>";
            echo "<source src='" . $song->getUrlFile() . "' type='audio/mpeg'>";
            echo "</audio><br><br>";
        }
    } else {
        echo "<p>No se encuentran canciones</p>";
    }

    ?>

</body>

</html>