<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap" rel="stylesheet">
    <title>Canciones</title>
    <style>
        body {
            background-color: #302f2f;
            color: #FFFFFF;
            font-family: 'Poppins', Arial, sans-serif;
        }

        input[type="submit"] {
            font-family: 'Poppins', Arial, sans-serif;
            background-color: #00A431;
            color: #FFFFFF;
            border-radius: 5px;
            padding: 5px;
            text-decoration: none;
        }

        input[type="text"] {
            font-family: 'Poppins', Arial, sans-serif;
        }

        a {
            color: #00A431;
        }
    </style>
</head>

<body>

    <h1>Canciones</h1>

    <h2>Tus canciones</h2>

    <?php
    if ($userSongs) {
        foreach ($userSongs as $userSong) {
            echo $userSong->getTitle() . " - " . $userSong->getAuthor() . "<br><br>";
            echo "<audio controls>";
            echo "<source src='" . $userSong->getUrlFile() . "' type='audio/mpeg'>";
            echo "</audio><br><br>";
        }
    } else {
        echo "<p>No tienes canciones creadas</p>";
    }

    ?>

    <hr>


    <h2>Todas las canciones</h2>

    <form action="index.php?c=song" method="POST">
        <input type="text" name="searchSong" placeholder="Buscar canción">
        <select name="searchType">
            <option value="title">Título</option>
            <option value="author">Autor</option>
        </select>
        <input type="submit" value="Buscar">
    </form><br>


    <?php
    if ($songs) {
        foreach ($songs as $song) {
            echo $song->getTitle() . " - " . $song->getAuthor() . "<br><br>";
            echo "<audio controls>";
            echo "<source src='" . $song->getUrlFile() . "' type='audio/mpeg'>";
            echo "</audio><br><br>";
    ?>

            <form action="index.php?c=song&addSongToPlaylist=1&songId=<?php $song->getId() ?>" method="POST">
                <input list="playlists" name="playlists" id="playlist" placeholder="Añadir a playlist...">
                <datalist id="playlists">
                    <?php
                    foreach ($playlists as $playlist) {
                        echo "<option value='" . $playlist->getTitle() . "'>";
                    }
                    ?>

                </datalist>
                <input type="submit" value="Añadir">
            </form><br>

    <?php
        }
    } else {
        echo "<p>No se encuentran canciones</p>";
    }

    ?>

</body>

</html>