<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Usuarios</title>
</head>

<body>

    <h1>Lista de usuarios</h1>

    <ul>
        <?php
        foreach ($users as $user) {
			echo '<li><a href="index.php?c=userDetail&showUniqueUser=1&id=' . $user->getId() . '">' . $user->getUsername() . "</a></li>";
        }
        ?>
    </ul>


    <a href="index.php">Volver a la lista de películas</a>

</body>

</html>