<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detalles de la película</title>
</head>

<body>
<ul>
		<?php

			$image = "./public/img/" . $movie[0]->getImage();

			echo '<h2><a href="index.php?c=movie&showUniqueMovie=1&id=' . $movie[0]->getId() . '">' . $movie[0]->getTitle() . ' (Estrenado en ' . $movie[0]->getYear() . ')</a></h2>';
			echo "<img src='" . $image . "' alt='" . $movie[0]->getTitle() . "' width='200' height='300'><br><br>";
			echo '<a href="index.php?likeMovie=1&id=' . $movie[0]->getId() . '">Me gusta</a>&nbsp;' . $movie[0]->getLikes() . '<br><br>';
			echo '<a href="index.php?deleteMovie=1&id=' . $movie[0]->getId() . '">Eliminar</a><br><br>';
	

		?>
	</ul>

    <a href="index.php">Volver a la lista de películas</a>
</body>

</html>
